language: cpp

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "msu35DqC82uGxfwO3JuF+YdZsef0hcN9xpUNZ6exmfcCNE+gV0N4+wdtK5CRd9tXMBv1huKDQiPf3RrJZ8u7P/xubCFb7uAFlyK/9JVX6h1xUDLO69kcyHRvZJqoq3QtpE/IvtInjlhadur6tRqoZb5LAXBN8zdw2bqWoBrQ1b3NYJv50ud7h4/AkaHPqUDxVHpKl0BgqbK0AIwMdrjLsYyWKYYUi8s1qlUavtX6ohNsH+/LLKC0yhMY8/aqHd1qil5sSARGOeWrfCCNQxXARzY/CXByqsVJHW9UoN2Yp87HmHFCJIP6PfVahtpvHdio9uC/hRgsvafdXrpNtHjxE41PW4BxeBSL+vEn3I4oFKC2PI5M93rBD3s0jKBoTeBmKPO/yIsxcHvvoNP1laXBYfnjbxn4ldnXPkfyCBK+dj9lk1fQ1Rj353EHi25ifqhffAFzSNwbuBNzPrf0OOxUYE5NGT2S3kIYiOvO25EFVmRYy62jvrd2YxfLrUH7p7afJH22Zlsd06a1YF+e57IupYS5uodZoYX2UsGXW21kCmWC8zGO7cnZ8TBv0jcwa0Uh4uasJBbS2zaGU6odc4z+PNpMenLrpHUX6Qx5JXHoepBH8KjkhgQ2mP3MDZFX0DiOGfTcgoJSMeTY8ncPXZ25i/Kvel8blljP3sAeIi7U2ng="

os:
  - linux

compiler:
  - clang
  - gcc

matrix:
  include:
  - os: osx
    osx_image: xcode8

addons:
  apt:
    packages:
    - gcc
    - bison
    - flex
    - libpugixml-dev
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-mixer-dev
    - libglew-dev
  coverity_scan:
    project:
      name: "dreamchess/dreamchess"
      description: "Build submitted via Travis CI"
    notification_email: feedback@dreamchess.org
    build_command_prepend: "mkdir build && cd build && cmake .."
    build_command: "make"
    branch_pattern: coverity_scan

before_install:
  - test $TRAVIS_BRANCH != coverity_scan -o ${TRAVIS_JOB_NUMBER##*.} = 1 || exit 0
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2 sdl2_image sdl2_mixer pugixml glew; fi

script:
  - test $TRAVIS_BRANCH != coverity_scan || exit 0
  - mkdir build
  - cd build
  - cmake ..
  - make

before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cpack -G DragNDrop; fi

deploy:
  provider: releases
  api_key:
    secure: mmfiOyTwEkQUTsaYkJbr/2yLJZxbU/VfEafhFlr/yhP9BNnZ8sUR5YelgzsiC+GnIJQDsQLKBz+4sh+I5Jg8nemIP2nVb+2NE1OryggIjVjUNlK5/SKMtoGNruRlJ1c3tCfCHEbxoCCtYvwvQipeb6uHX8GQ1J3kpvD8Ii1hjUBTHgGDy3RkdG2PoFbLc4fzlvS/0AbqRWe6m/g8fxrmuZ0hssyvzRA++GA/yv2A2ZS7kDruvfRRYz0tziEVArQuSHpLqRc6JXB/bywhLMOQIPuyQdISGng8hTG+DkUeEUuL4w2mn/DV4XkFQF9KnUWb+Lmbbkh6Wv/FoW2Kp0WJaMVuLi8xM06/BLGoItm/dk6x2uZs6QiVtPSefudlU9SJ0JjzQ5zOEv/OJcDR0Gv4AJzCJ76ZzDrq+/cXqlFj9D7Tblcj2Fbo0E33bEn9/gL6RiUb+z+I50QE/9ELfH72He3bovKOtI6ZyaqiEhv7ti79uZZZikpvkibRc/oMZDJIgwTRB/NxWQUz64SDc9UYREws2DXyROcmvaavx7RvKxuFVXjQNr2jYnZaAXnWiLAhm7bYYtRrM0tWnfVDuFdLbX3N640z+v4D9U/XyN5Zi6wtaItM2BCOh6v1tmfIQfv2LTpNJTNlQCDhjrK2+/T4iQJ3kisV0jSzgJrilJKIsfM=
  draft: true
  tag_name: $TRAVIS_TAG
  name: DreamChess $TRAVIS_TAG
  file_glob: true
  file: "*.dmg"
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
