language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "msu35DqC82uGxfwO3JuF+YdZsef0hcN9xpUNZ6exmfcCNE+gV0N4+wdtK5CRd9tXMBv1huKDQiPf3RrJZ8u7P/xubCFb7uAFlyK/9JVX6h1xUDLO69kcyHRvZJqoq3QtpE/IvtInjlhadur6tRqoZb5LAXBN8zdw2bqWoBrQ1b3NYJv50ud7h4/AkaHPqUDxVHpKl0BgqbK0AIwMdrjLsYyWKYYUi8s1qlUavtX6ohNsH+/LLKC0yhMY8/aqHd1qil5sSARGOeWrfCCNQxXARzY/CXByqsVJHW9UoN2Yp87HmHFCJIP6PfVahtpvHdio9uC/hRgsvafdXrpNtHjxE41PW4BxeBSL+vEn3I4oFKC2PI5M93rBD3s0jKBoTeBmKPO/yIsxcHvvoNP1laXBYfnjbxn4ldnXPkfyCBK+dj9lk1fQ1Rj353EHi25ifqhffAFzSNwbuBNzPrf0OOxUYE5NGT2S3kIYiOvO25EFVmRYy62jvrd2YxfLrUH7p7afJH22Zlsd06a1YF+e57IupYS5uodZoYX2UsGXW21kCmWC8zGO7cnZ8TBv0jcwa0Uh4uasJBbS2zaGU6odc4z+PNpMenLrpHUX6Qx5JXHoepBH8KjkhgQ2mP3MDZFX0DiOGfTcgoJSMeTY8ncPXZ25i/Kvel8blljP3sAeIi7U2ng="

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - gcc
    - bison
    - flex
    - libmxml-dev
    - libsdl1.2-dev
    - libsdl-image1.2-dev
    - libsdl-mixer1.2-dev
    - libglew-dev
  coverity_scan:
    project:
      name: "DreamChess"
      description: "Build submitted via Travis CI"
    notification_email: feedback@dreamchess.org
    build_command_prepend: "mkdir build && cd build && cmake .."
    build_command: "make"
    branch_pattern: coverity_scan

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mkdir build && cd build && cmake .. && make; fi
